version: '2.1'
services:
  db:
    image: 'postgres:13.7-alpine'
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - simple_network
  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
    ports:
      - 8000:80
    networks:
      - simple_network

networks:
  simple_network:
    name: simple_network
