version: '2.1'
services:
  db:
    image: 'postgres:13'
    environment:
      - POSTGRES_DB=aluraflix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - simple_network
  app:
    build: .
    environment:
      - DB_NAME=aluraflix
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
    ports:
      - 8000:80
    networks:
      - simple_network
    depends_on:
      - db

networks:
  simple_network:
    name: simple_network
