version: '2.1'
services:
  db:
    image: 'postgres:13'
    environment:
      - POSTGRES_DB=aluraflix
    env_file: db.env.local
    networks:
      - simple_network
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=aluraflix
      - ENV_NAME=Development
    env_file: app.env.local
    ports:
      - 8000:8000
    networks:
      - simple_network
    depends_on:
      - db

networks:
  simple_network:
    name: simple_network

volumes:
  db_data:
    name: aluraflix_postgres_data
