name: Continuous Deployment
# on:
#   push:
#     branches:
#       - master
on: [push]

jobs:
  wait-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for ci to be succeded
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Exit with a failing build
        if: steps.wait-for-ci.outputs.conclusion == 'failure'
        run: exit 1

